## Button Texts

button_text_start = Start
button_text_apply = Apply
button_text_proceed = Proceed
button_text_ok = Ok

button_text_reset = Reset
button_text_cancel = Cancel
button_text_back = Back

button_text_yes = Yes
button_text_no = No

# Colors
color_red = Red
color_green = Green
color_blue = Blue
color_alpha = Alpha
color_hint_copypaste_hex = Copy and paste hex values into here

# General File Operations

FileOperationStatus_saved_message=%s saved successfully
FileOperationStatus_loaded_message=%s loaded successfully
FileOperationStatus_deleted_message=%s deleted successfully
FileOperationStatus_aborted_message=File operation aborted
FileOperationStatus_failed_message=File operation has failed with an error

# Message Type

MessageType_success_name=Success
MessageType_info_name=Info
MessageType_warning_name=Warning
MessageType_alert_name=Alert
MessageType_exception_name=Error

# Paginator

paginator_page = Page %s / %s

# Zoom Buttons

tooltip_zoom_in = Zoom Out
tooltip_zoom_out = Zoom In
tooltip_zoom_reset = Reset Zoom
