plugins {
  id 'net.nemerosa.versioning' version '2.6.1'
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"

  implementation group: 'org.json', name: 'json', version: '20210307'
  implementation "space.earlygrey:shapedrawer:2.5.0"
  implementation 'junit:junit:4.13.1'
  implementation 'org.junit.jupiter:junit-jupiter:5.8.1'
  testImplementation('org.junit.jupiter:junit-jupiter-api:5.4.2')
  testImplementation('org.junit.jupiter:junit-jupiter-engine:5.4.2')
  implementation("org.xerial:sqlite-jdbc:3.49.1.0")
  implementation('org.junit.jupiter:junit-jupiter-api:5.4.2')
  implementation('org.junit.jupiter:junit-jupiter-engine:5.4.2')

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

task dist(type: Jar) {
  manifest {
    attributes(
      'AppName'        : appName,
      'AppVersion'     : version,
      'Build-Timestamp': new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(new Date()),
      'Build-Revision' : versioning.info.commit,
      'Created-By'     : "Gradle ${gradle.gradleVersion}",
    )
  }
}
