plugins {
  id 'maven-publish'
  id 'net.nemerosa.versioning' version '2.6.1'
}

def subprojectName = 'core'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-tools:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  // https://mvnrepository.com/artifact/org.json/json
  implementation group: 'org.json', name: 'json', version: "$jsonVersion"
  implementation "space.earlygrey:shapedrawer:$shapeDrawerVersion"
  testImplementation("org.junit.jupiter:junit-jupiter-api:$jUnitVersion")
  testImplementation("org.junit.jupiter:junit-jupiter-engine:$jUnitVersion")
  testImplementation("org.junit.jupiter:junit-jupiter-params:$jUnitVersion")
  implementation("org.junit.jupiter:junit-jupiter-api:$jUnitVersion")
  implementation("org.junit.jupiter:junit-jupiter-engine:$jUnitVersion")

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

test {
  useJUnitPlatform()
  maxHeapSize = '1G'
}

jar {
  // define source directory
  sourceSets.main.java.srcDirs = [ "src/main/java" ]
  archivesBaseName = appName + '-core'
  manifest {
    attributes(
      'AppName'        : "${archivesBaseName}",
      'AppVersion'     : version,
      'Build-Timestamp': new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(new Date()),
      'Build-Revision' : versioning.info.commit,
      'Created-By'     : "Gradle ${gradle.gradleVersion}",
    )
  }
}

publishing {
  publications {
    maven(MavenPublication) {
      groupId = 'com.neutronio.phi'
      artifactId = archivesBaseName
      version = version

      from components.java
    }
  }
}

